# Database Configuration
spring.datasource.url=jdbc:sqlserver://petlo.database.windows.net:1433;database=Shoes;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=sneaker@petlo
spring.datasource.password=@Nike123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true

# Server Configuration
server.servlet.context-path=/api

# AWS Configuration
aws.accessKeyId=AKIA2L7IBH3ZQDLEP3XP
aws.secretKey=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
aws.region=eu-north-1
aws.s3.bucket=african-arts-and-crafts-bucket

